openapi: 3.0.0
info:
  title: Seryu API
  version: 1.0.0
  description: API Seryu for managing operations.
servers:
  - url: http://localhost:3000

paths:
  /api/v1/salary/driver/list:
    $ref: './paths/salary-driver-list.yaml'

components:
  schemas:
    DriverSalary:
      $ref: './components/DriverSalary.yaml'
